name: Deploy service

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Select environment"
        required: true
        default: "stage"
        type: choice
        options:
          - stage
          - prod

run-name: "Deploy svc-payment to '${{ input.env }}' by ${{ github.actor }}"

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_OPTIONS: "--max_old_space_size=4096"
  DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}

jobs:
  publish:
    name: Deploy service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code ğŸ“
        uses: actions/checkout@v3

      - name: Install Deno â¬‡ï¸
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup environment âš’ï¸
        run: deno task env:${{ inputs.env }}

      # - name: Generate db client âš’ï¸
      #   run: deno task db:generate

      # - name: Test ğŸ¥‘
      #   run: deno task test

      - name: Preview ğŸ‘€
        run: deno task preview & sleep 2 && kill $!
      
      - name: Install deployctl â¬‡ï¸
        run: deno install -A -r -f https://deno.land/x/deploy/deployctl.ts

      - name: Deploy ğŸš€
        run: deno task deploy:${{ inputs.env }}